CREATE TABLE app_user
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id         BIGINT,
    organization_request_id BIGINT,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

CREATE TABLE app_user_details
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_user_id        BIGINT,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    last_name          VARCHAR(255)                            NOT NULL,
    registration_token VARCHAR(255),
    is_enabled         BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_appuserdetails PRIMARY KEY (id)
);

CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    menu_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE company
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE company_notification_config
(
    id                   BIGINT NOT NULL,
    preference_config_id BIGINT NOT NULL,
    CONSTRAINT pk_companynotificationconfig PRIMARY KEY (id)
);

CREATE TABLE company_order
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_date_time TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(255),
    is_deleted         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_companyorder PRIMARY KEY (id)
);

CREATE TABLE company_preference_config
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id            BIGINT                                  NOT NULL,
    company_discount_type VARCHAR(255),
    delivery_address      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_companypreferenceconfig PRIMARY KEY (id)
);

CREATE TABLE employee_notification_config
(
    id          BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    CONSTRAINT pk_employeenotificationconfig PRIMARY KEY (id)
);

CREATE TABLE employee_order
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted                BOOLEAN                                 NOT NULL,
    company_order_id          BIGINT,
    supplier_default_price    DOUBLE PRECISION                        NOT NULL,
    supplier_discounted_price DOUBLE PRECISION                        NOT NULL,
    final_price               DOUBLE PRECISION                        NOT NULL,
    status                    VARCHAR(255),
    CONSTRAINT pk_employeeorder PRIMARY KEY (id)
);

CREATE TABLE employee_preference_config
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    notification_config_id BIGINT                                  NOT NULL,
    employee_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_employeepreferenceconfig PRIMARY KEY (id)
);

CREATE TABLE employees_orders_options
(
    employee_order_id BIGINT NOT NULL,
    option_id         BIGINT NOT NULL,
    CONSTRAINT pk_employees_orders_options PRIMARY KEY (employee_order_id, option_id)
);

CREATE TABLE lunch_subscriptions
(
    company_id  BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    CONSTRAINT pk_lunch_subscriptions PRIMARY KEY (company_id, supplier_id)
);

CREATE TABLE lunch_subscriptions_requests
(
    company_id  BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    CONSTRAINT pk_lunch_subscriptions_requests PRIMARY KEY (company_id, supplier_id)
);

CREATE TABLE menu
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

CREATE TABLE notification_config
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIME WITHOUT TIME ZONE,
    amount     INTEGER                                 NOT NULL,
    interval   numeric(21, 0),
    CONSTRAINT pk_notificationconfig PRIMARY KEY (id)
);

CREATE TABLE option
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id BIGINT                                  NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_option PRIMARY KEY (id)
);

CREATE TABLE option_description
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN                                 NOT NULL,
    option_id  BIGINT                                  NOT NULL,
    value      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_optiondescription PRIMARY KEY (id)
);

CREATE TABLE order_capacity
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preference_config_id    BIGINT                                  NOT NULL,
    duration                numeric(21, 0),
    employees_orders_amount INTEGER                                 NOT NULL,
    CONSTRAINT pk_ordercapacity PRIMARY KEY (id)
);

CREATE TABLE organization
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    email       VARCHAR(255)                            NOT NULL,
    phone       VARCHAR(255)                            NOT NULL,
    logo        OID,
    deleted     BOOLEAN DEFAULT FALSE                   NOT NULL,
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

CREATE TABLE price_by
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preference_config_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_priceby PRIMARY KEY (id)
);

CREATE TABLE price_by_category
(
    id     BIGINT           NOT NULL,
    amount INTEGER          NOT NULL,
    price  DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_pricebycategory PRIMARY KEY (id)
);

CREATE TABLE price_by_option
(
    id        BIGINT           NOT NULL,
    option_id BIGINT           NOT NULL,
    price     DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_pricebyoption PRIMARY KEY (id)
);

CREATE TABLE supplier
(
    id          BIGINT NOT NULL,
    website_url bytea  NOT NULL,
    menu_url    bytea  NOT NULL,
    CONSTRAINT pk_supplier PRIMARY KEY (id)
);

CREATE TABLE supplier_preference_config
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    supplier_id                BIGINT                                  NOT NULL,
    request_offset             numeric(21, 0)                          NOT NULL,
    delivery_period_start_time TIME WITHOUT TIME ZONE                  NOT NULL,
    delivery_period_end_time   TIME WITHOUT TIME ZONE                  NOT NULL,
    minimum_orders_per_request INTEGER DEFAULT 1                       NOT NULL,
    order_type                 VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_supplierpreferenceconfig PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT       NOT NULL,
    role    VARCHAR(255) NOT NULL
);

ALTER TABLE app_user_details
    ADD CONSTRAINT uc_appuserdetails_email UNIQUE (email);

ALTER TABLE organization
    ADD CONSTRAINT uc_organization_email UNIQUE (email);

ALTER TABLE organization
    ADD CONSTRAINT uc_organization_name UNIQUE (name);

ALTER TABLE app_user_details
    ADD CONSTRAINT FK_APPUSERDETAILS_ON_APP_USER FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE app_user
    ADD CONSTRAINT FK_APPUSER_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organization (id);

ALTER TABLE app_user
    ADD CONSTRAINT FK_APPUSER_ON_ORGANIZATION_REQUEST FOREIGN KEY (organization_request_id) REFERENCES organization (id);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_MENU FOREIGN KEY (menu_id) REFERENCES menu (id);

ALTER TABLE company_notification_config
    ADD CONSTRAINT FK_COMPANYNOTIFICATIONCONFIG_ON_ID FOREIGN KEY (id) REFERENCES notification_config (id);

ALTER TABLE company_notification_config
    ADD CONSTRAINT FK_COMPANYNOTIFICATIONCONFIG_ON_PREFERENCE_CONFIG FOREIGN KEY (preference_config_id) REFERENCES company_preference_config (id);

ALTER TABLE company_preference_config
    ADD CONSTRAINT FK_COMPANYPREFERENCECONFIG_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE company
    ADD CONSTRAINT FK_COMPANY_ON_ID FOREIGN KEY (id) REFERENCES organization (id);

ALTER TABLE employee_notification_config
    ADD CONSTRAINT FK_EMPLOYEENOTIFICATIONCONFIG_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee_preference_config (id);

ALTER TABLE employee_notification_config
    ADD CONSTRAINT FK_EMPLOYEENOTIFICATIONCONFIG_ON_ID FOREIGN KEY (id) REFERENCES notification_config (id);

ALTER TABLE employee_order
    ADD CONSTRAINT FK_EMPLOYEEORDER_ON_COMPANY_ORDER FOREIGN KEY (company_order_id) REFERENCES company_order (id);

ALTER TABLE employee_preference_config
    ADD CONSTRAINT FK_EMPLOYEEPREFERENCECONFIG_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES app_user (id);

ALTER TABLE employee_preference_config
    ADD CONSTRAINT FK_EMPLOYEEPREFERENCECONFIG_ON_NOTIFICATION_CONFIG FOREIGN KEY (notification_config_id) REFERENCES employee_notification_config (id);

ALTER TABLE menu
    ADD CONSTRAINT FK_MENU_ON_SUPPLIER FOREIGN KEY (supplier_id) REFERENCES supplier (id);

ALTER TABLE option_description
    ADD CONSTRAINT FK_OPTIONDESCRIPTION_ON_OPTION FOREIGN KEY (option_id) REFERENCES option (id);

ALTER TABLE option
    ADD CONSTRAINT FK_OPTION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE order_capacity
    ADD CONSTRAINT FK_ORDERCAPACITY_ON_PREFERENCE_CONFIG FOREIGN KEY (preference_config_id) REFERENCES supplier_preference_config (id);

ALTER TABLE price_by_category
    ADD CONSTRAINT FK_PRICEBYCATEGORY_ON_ID FOREIGN KEY (id) REFERENCES price_by (id);

ALTER TABLE price_by_option
    ADD CONSTRAINT FK_PRICEBYOPTION_ON_ID FOREIGN KEY (id) REFERENCES price_by (id);

ALTER TABLE price_by_option
    ADD CONSTRAINT FK_PRICEBYOPTION_ON_OPTION FOREIGN KEY (option_id) REFERENCES option (id);

ALTER TABLE price_by
    ADD CONSTRAINT FK_PRICEBY_ON_PREFERENCE_CONFIG FOREIGN KEY (preference_config_id) REFERENCES supplier_preference_config (id);

ALTER TABLE supplier_preference_config
    ADD CONSTRAINT FK_SUPPLIERPREFERENCECONFIG_ON_SUPPLIER FOREIGN KEY (supplier_id) REFERENCES supplier (id);

ALTER TABLE supplier
    ADD CONSTRAINT FK_SUPPLIER_ON_ID FOREIGN KEY (id) REFERENCES organization (id);

ALTER TABLE employees_orders_options
    ADD CONSTRAINT fk_empordopt_on_employee_order FOREIGN KEY (employee_order_id) REFERENCES employee_order (id);

ALTER TABLE employees_orders_options
    ADD CONSTRAINT fk_empordopt_on_option FOREIGN KEY (option_id) REFERENCES option (id);

ALTER TABLE lunch_subscriptions
    ADD CONSTRAINT fk_lunsub_on_company FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE lunch_subscriptions
    ADD CONSTRAINT fk_lunsub_on_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id);

ALTER TABLE lunch_subscriptions_requests
    ADD CONSTRAINT fk_lunsubreq_on_company FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE lunch_subscriptions_requests
    ADD CONSTRAINT fk_lunsubreq_on_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_app_user_details FOREIGN KEY (user_id) REFERENCES app_user_details (id);
