pipeline {
    agent any
    stages {
        stage('Dockerize Frontend Vue3/Vite Application') {
            steps {
                sh "cd frontend && sudo docker build -t -e BACKEND_URL=http://104.248.80.209:8081 blp-frontend ."
                sh 'cd frontend && sudo docker run -d -p 4173:4173 -e BACKEND_URL=http://104.248.80.209:8081 blp-frontend'
            }
        }
    }
    post {
        failure {
            mail to: 'blp.app.team@gmail.com',
                 subject: "Build failed: ${currentBuild.fullDisplayName}",
                 body: "Something went wrong with ${env.BUILD_URL}"
        }
    }
}
