export enum CategoryTag {
  BURGERS = "Burgers",
  PIZZA = "Pizza",
  SUSHI = "Sushi",
  KEBAB = "Kebab",
  PASTRY = "Pastry",
  STEAK = "Steak",
  BBQ = "BBQ",
  PASTA = "Pasta",
  SEAFOOD = "Seafood",
  WOK = "Wok",
  MEDITERRANEAN = "Mediterranean",
  TRADITIONAL = "Traditional",
  BREAKFAST = "Breakfast",
  PANCAKES = "Pancakes",
  ORIENTAL = "Oriental",
  VEGETARIAN = "Vegetarian",
  SALADS = "Salads",
  DESSERTS = "Desserts",
  OTHER = "Other"
}
