pipeline {
    agent any
    stages {
        stage('Build and Test Backend Spring Boot Application') {
            steps {
                dir('/backend-apps/backend') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Build Frontend Vue3/Vite Application') {
            steps {
                dir('/frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        stage('Dockerize Backend Spring Boot Application') {
            steps {
                dir('/backend-apps/backend') {
                    sh "docker build -t blp-backend ."
                    sh 'docker run -d -p 8080:8080 -e BACKEND_URL=http://104.248.80.209:8081 -e FRONTEND_URL=http://104.248.80.209:3000 -e DISCOVERY-ADDRESS=104.248.80.209:5050 -e DATABASE_ADDRESS=104.248.80.209:5432 blp-backend'
                }
            }
        }
        stage('Dockerize Frontend Vue3/Vite Application') {
            steps {
                dir('/frontend') {
                    sh "docker build -t blp-frontend ."
                    sh 'docker run -d -p 3000:3000 blp-frontend'
                }
            }
        }
    }
    post {
        failure {
            mail to: 'blp.app.team@gmail.com',
                 subject: "Build failed: ${currentBuild.fullDisplayName}",
                 body: "Something went wrong with ${env.BUILD_URL}"
        }
    }
}
