pipeline {
    agent any
    stages {
        stage('Build and Test Backend Spring Boot Application') {
            steps {
                sh 'cd backend-apps && cd backend && sudo mvn clean verify'
            }
        }
        stage('Dockerize Backend Spring Boot Application') {
            steps {
                sh 'cd backend-apps && cd backend && sudo docker build -t blp-backend .'
                sh 'cd backend-apps && cd backend && sudo docker run -d -p 8081:8081 -e BACKEND_URL=http://104.248.80.209:8081 -e FRONTEND_URL=http://104.248.80.209:4173 -e DISCOVERY-ADDRESS=104.248.80.209:5050 -e DATABASE_ADDRESS=104.248.80.209:5432 TOKEN_VAULT=$vault_token blp-backend'
            }
        }
    }
    post {
        failure {
            mail to: 'blp.app.team@gmail.com',
                 subject: "Build failed: ${currentBuild.fullDisplayName}",
                 body: "Something went wrong with ${env.BUILD_URL}"
        }
    }
}
