lunch:
  backend:
    url: ${BACKEND_URL}
    users:
      generate:
        default: true
  frontend:
    url: ${FRONTEND_URL}
  discovery:
    address: ${DISCOVERY_ADDRESS}

server:
  port: 8081

spring:
  cloud:
    vault:
      scheme: http
      host: 104.248.80.209
      port: 8200
