lunch:
  backend:
    url: http://localhost:8080
    users:
      generate:
        default: true
  frontend:
    url: http://localhost:3000
  discovery:
    address: localhost:8761
  database:
    address: localhost:5432
spring:
  cloud:
    vault:
      uri: http://localhost:8200
