lunch:
  backend:
    url: ${BACKEND_URL}
    users:
      generate:
        default: true
  frontend:
    url: ${FRONTEND_URL}
  discovery:
    address: ${DISCOVERY_ADDRESS}
  database:
    address: ${DATABASE_ADDRESS}
