version: '3.8'

services:
  ###########################################################################################
  database:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: business-lunch-provider-db
  ###########################################################################################
  vault:
    image: vault:1.12.2
    ports:
      - "8200:8200"
    environment:
      - cap-add=IPC_LOCK
      - VAULT_DEV_ROOT_TOKEN_ID=${TOKEN_VAULT}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
  ###########################################################################################
  vault-hack:
    image: vault:1.12.2
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${TOKEN_VAULT}
    command: >
      sh -c ' sleep 5
      && date
      && vault kv put secret/blp-discovery 
      lunch.discovery.username=admin lunch.discovery.password=admin
      && vault kv put secret/blp-backend 
      lunch.discovery.username=admin lunch.discovery.password=admin 
      lunch.jwt.secret=dummySecret lunch.database.username=db_user 
      lunch.database.password=db_password lunch.mail.username=${BLP_EMAIL_USER} 
      lunch.mail.password="$BLP_EMAIL_PASS"
      lunch.backend.actuator.username=actuator lunch.backend.actuator.password=admin
      spring.security.user.name=actuator spring.security.user.password=admin
      && vault kv put secret/blp-spring-admin 
      lunch.monitoring.username=admin lunch.monitoring.password=admin
      lunch.discovery.username=admin lunch.discovery.password=admin 
      lunch.backend.actuator.username=actuator lunch.backend.actuator.password=admin
      && date
      && exit'
